'use server';

import { redirect } from 'next/navigation';
import { createClient } from '@/lib/supabase/server';

export async function joinMembership() {
  const supabase = createClient();

  const {
    data: { user },
  } = await supabase.auth.getUser();

  if (!user) {
    redirect('/login?redirect=/members/join');
  }

  // Idempotent — profile_id is unique, so this is a no-op if they already
  // have a membership row (e.g. double-submit). status defaults to 'active'
  // and discount_code is auto-generated by a DB default; payment isn't
  // wired yet, so stripe_payment_intent_id stays null for now.
  const { error } = await supabase
    .from('memberships')
    .upsert({ profile_id: user!.id }, { onConflict: 'profile_id' });

  if (error) {
    redirect('/members/join?error=' + encodeURIComponent(error.message));
  }

  redirect('/members');
}
